easy_admin:
    entities:
        Film:
            class: App\Entity\Film
            label: 'Films'
            list:
                fields:
                    - { property: titre, label: 'Titre' }
                    - { property: 'imageName', type: 'image', base_path: '%app.path.films_image%' }
            form:
                title: "Modification/édition"
                fields:
                    - { property: titre, label: 'Titre' }
                    - { property: 'imageFile', type: 'vich_image', label: 'Affiche'  }