parameters:
    app.path.films_image: /uploads/films
    
vich_uploader:
    db_driver: orm

    mappings:
        film_affiche:
            uri_prefix:         '%app.path.films_image%'
            upload_destination: '%kernel.root_dir%/../public%app.path.films_image%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true