version: '3'
services:
  app:
    build: .
    ports:
      - 8000
    volumes:
      - ./:/var/www
    command: ["php", "-S", "0.0.0.0:8000", "-t", "/var/www/public"]
    environment:
      DATABASE_URL: sqlite:///%kernel.project_dir%/var/data.db